language: r
cache: packages
warnings_are_errors: true
sudo: required
dist: trusty

r_github_packages:
  - vnijs/shinyAce
  - radiant-rstats/radiant.data
  - radiant-rstats/radiant.design
  - radiant-rstats/radiant.basics
  - radiant-rstats/radiant.model
  - radiant-rstats/radiant.multivariate
